### ISSUE TITLE
How can I get this to work with a tab bar controller?

### ISSUE THREAD

**Issue by ryandailey100** [marty-suzuki/SAInboxViewController#16]
It works perfect without a tabbar controller, but when i add the tab bar controller, it seems to cause some issues. The animation does not work, instead, it switches to the next view controller default IOS style (instead doing the inbox effect). Please help, thanks!

**Comment by marty-suzuki** [comment]
Thank you for your issue.
SAInboxViewController works with UINavigationController.

**Comment by ryandailey100** [comment]
Yes I am using a NavigationController in my project. How can I get it working with a tab bar controller?

**Comment by ryandailey100** [comment]
This class also doesnt seem to work when there is a view controller above the NavigationController. For example, my app starts off with a login, then I want it to show the tableview. But when there is a view controller above the NavigationController, everything seems to break. This also applies to a TabBarController. Any way to fix this?

**Comment by marty-suzuki** [comment]
> a view controller above the NavigationController

Does it means ViewController is presenting by NavigationController or ViewController is one of stack in NavigationController?

This transitioning only works between SAInboxViewController subclass and SAInboxDetailViewController subclass via UINavigationController.

**Comment by ryandailey100** [comment]
<img width="489" alt="screen shot 2016-12-28 at 4 35 33 am" src="https://cloud.githubusercontent.com/assets/15038444/21518857/1da32a30-ccb7-11e6-941b-391f90313fd5.png">

Here is an example. Keep in mind that the entry point is NOT on the NavigationController. 
PS: When the entry point is on the NavigationController, everything works okay. My issue is that for my app, the entry point will be on another view controller (just like how it is in the picture)

**Comment by marty-suzuki** [comment]
Thank you for your screenshot.
I realized now, what is a real issue. I'm sorry.

In you app case, where is UINavigationControllerDelegate implementation?

**Comment by ryandailey100** [comment]
I have the UINavigationControllerDelegate in the AppDelegate.

**Comment by marty-suzuki** [comment]
Where do you set navigationController.delegate?

**Comment by ryandailey100** [comment]
<img width="868" alt="screen shot 2016-12-28 at 4 58 53 am" src="https://cloud.githubusercontent.com/assets/15038444/21519348/642a8a90-ccba-11e6-9285-33518cf60be4.png">

Is this what you mean? By the way, I have this project set up the same way as in the sample project that you have provided.

**Comment by marty-suzuki** [comment]
In your case, initialViewController of Storyboard is ViewController.
Therefore, `window?.rootViewController as? UINavigationController` returns nil.
You have to get NavigationController instance from segue and so on in a UIViewController.
If you can get navigationController, you set `navigationController.delegate = self` and implement `UINavigationControllerDelegate` in a UIViewController.

**Comment by ryandailey100** [comment]
Sorry but what do you mean by "You have to get NavigationController instance from segue and so on in a UIViewController" ?

This is what I did so far, but still no luck.
<img width="846" alt="screen shot 2016-12-28 at 5 19 01 am" src="https://cloud.githubusercontent.com/assets/15038444/21519713/5f73c9dc-ccbd-11e6-86df-e23bd4200170.png">

**Comment by marty-suzuki** [comment]
In you case, navigationController does not exist yet.
Please read storyboard basic knowledge.
https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/UsingSegues.html

**Comment by ryandailey100** [comment]
Okay I finally got everything working! Thank you so much for answering all my questions.
